### ISSUE TITLE
Remove masks from repo

### ISSUE THREAD

**Issue by Molesmalo** [fabiospampinato/airmash-swam-extensions#1]
Hi Moz!

In the hit circles theme, think you didn't modify the following files:

- map_rock_mask.jpg

- map_sand_mask.jpg

- map_sea_mask.jpg

So, those files could be removed from the customFiles array (so they are served from AM's server instead 😄 ).

**Comment by fabiospampinato** [comment]
Done, thanks for the suggestion :+1:
